import { env } from "../../config/env";

export interface LlmGenerateOptions {
  temperature?: number;
  maxTokens?: number;
}

export interface CloudLlmProvider {
  generate(prompt: string, options?: LlmGenerateOptions): Promise<string>;
}

export function getCloudLlmProvider(): CloudLlmProvider {
  if (env.llmProvider === "openai") {
    return new OpenAIProvider();
  }
  if (env.llmProvider === "gemini") {
    return new GeminiProvider();
  }
  if (env.llmProvider === "deepseek") {
    return new DeepSeekProvider();
  }
  if (env.llmProvider === "openai-compatible" && env.llmBaseUrl) {
    return new OpenAICompatibleProvider();
  }
  return new MockDeckProvider();
}

class OpenAIProvider implements CloudLlmProvider {
  async generate(prompt: string, options: LlmGenerateOptions = {}): Promise<string> {
    if (!env.openaiApiKey) throw new Error("OPENAI_API_KEY is required when LLM_PROVIDER=openai");
    return callOpenAICompatible({
      endpoint: "https://api.openai.com/v1/chat/completions",
      apiKey: env.openaiApiKey,
      model: env.openaiModel,
      prompt,
      options,
      providerName: "OpenAI",
    });
  }
}

class OpenAICompatibleProvider implements CloudLlmProvider {
  async generate(prompt: string, options: LlmGenerateOptions = {}): Promise<string> {
    if (!env.llmBaseUrl) throw new Error("LLM_BASE_URL is required when LLM_PROVIDER=openai-compatible");
    return callOpenAICompatible({
      endpoint: `${env.llmBaseUrl.replace(/\/$/, "")}/chat/completions`,
      apiKey: env.llmApiKey,
      model: env.llmModel,
      prompt,
      options,
      providerName: "OpenAI-compatible LLM",
    });
  }
}

class GeminiProvider implements CloudLlmProvider {
  async generate(prompt: string, options: LlmGenerateOptions = {}): Promise<string> {
    if (!env.geminiApiKey) throw new Error("GEMINI_API_KEY is required when LLM_PROVIDER=gemini");
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(
      env.geminiModel
    )}:generateContent`;
    const res = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": env.geminiApiKey,
      },
      body: JSON.stringify({
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: options.temperature ?? 0.4,
          maxOutputTokens: options.maxTokens ?? 3500,
        },
      }),
    });
    if (!res.ok) throw new Error(`Gemini request failed: ${res.status} ${await res.text()}`);
    const body = (await res.json()) as {
      candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>;
    };
    return body.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("") ?? "";
  }
}

class DeepSeekProvider implements CloudLlmProvider {
  async generate(prompt: string, options: LlmGenerateOptions = {}): Promise<string> {
    if (!env.deepseekApiKey) throw new Error("DEEPSEEK_API_KEY is required when LLM_PROVIDER=deepseek");
    return callOpenAICompatible({
      endpoint: "https://api.deepseek.com/chat/completions",
      apiKey: env.deepseekApiKey,
      model: env.deepseekModel,
      prompt,
      options,
      providerName: "DeepSeek",
    });
  }
}

async function callOpenAICompatible(input: {
  endpoint: string;
  apiKey: string;
  model: string;
  prompt: string;
  options: LlmGenerateOptions;
  providerName: string;
}): Promise<string> {
  const res = await fetch(input.endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(input.apiKey ? { Authorization: `Bearer ${input.apiKey}` } : {}),
    },
    body: JSON.stringify({
      model: input.model,
      temperature: input.options.temperature ?? 0.4,
      max_tokens: input.options.maxTokens ?? 3500,
      messages: [{ role: "user", content: input.prompt }],
    }),
  });
  if (!res.ok) throw new Error(`${input.providerName} request failed: ${res.status} ${await res.text()}`);
  const body = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
  return body.choices?.[0]?.message?.content ?? "";
}

class MockDeckProvider implements CloudLlmProvider {
  async generate(prompt: string): Promise<string> {
    const title = titleFromPrompt(prompt);
    const deck = {
      deckTitle: title,
      deckType: "general",
      designStyle: "modern",
      language: "en",
      summary: "Generated by the cloud agent mock provider. Configure LLM_PROVIDER=openai, LLM_PROVIDER=gemini, or LLM_PROVIDER=deepseek for real model output.",
      slides: [
        {
          slideNumber: 1,
          slideType: "title",
          title,
          subtitle: "Cloud generated presentation",
          bullets: ["Purpose, audience, and desired outcome"],
        },
        {
          slideNumber: 2,
          slideType: "overview",
          title: "Key Message",
          bullets: ["Clarify the main thesis", "Organize supporting points", "Prepare for follow-up refinement"],
        },
        {
          slideNumber: 3,
          slideType: "next_steps",
          title: "Next Steps",
          bullets: ["Review the generated outline", "Refine content and style", "Export when ready"],
        },
      ],
    };
    return [
      "I will create the deck artifact now.",
      "",
      "```tool",
      JSON.stringify({ name: "create_deck", arguments: { deck } }, null, 2),
      "```",
    ].join("\n");
  }
}

function titleFromPrompt(prompt: string): string {
  const match = /Project:\s*(.+)/i.exec(prompt) ?? /User request:\s*([\s\S]+?)(?:\n\n|$)/i.exec(prompt);
  const raw = (match?.[1] ?? "Untitled Cloud Deck").replace(/\s+/g, " ").trim();
  return raw.slice(0, 90) || "Untitled Cloud Deck";
}
